version: "3"
services:
  proxy:
    build: ./envoy
    ports:
      - "8080:8080"

  server:
    build: ./server
    ports:
      - "50051:50051"

  client:
    build: ./client
    ports:
      - "3000:3000"